<?php

namespace App\Services;

use App\Models\SubtitleCollection;

class AssExporter
{
    public function export(
        SubtitleCollection $subtitles,
        string $subtitleType = 'anime',
        array $styles = [],
        string $scriptInfo = '',
        string $projectGarbage = ''
    ): string {
        $ass = "[Script Info]\n";

        if (!empty($styles)) {
            $ass .= $scriptInfo . "\n";
        } else {
            $ass .= "; Script generated by Aegisub 3.4.2\n";
            $ass .= "; http://www.aegisub.org/\n";
            $ass .= "Title: Default Aegisub file\n";
            $ass .= "ScriptType: v4.00+\n";
            $ass .= "WrapStyle: 0\n";
            $ass .= "ScaledBorderAndShadow: yes\n";

            if ($subtitleType === 'anime') {
                $ass .= "\n";
            } elseif ($subtitleType === 'movie') {
                $ass .= "YCbCr Matrix: TV.709\n";
                $ass .= "PlayResX: 1280\n";
                $ass .= "PlayResY: 720\n\n";
            } else {
                $ass .= "\n";
            }
        }

        $ass .= "[Aegisub Project Garbage]\n";
        $ass .= $projectGarbage . "\n";

        $ass .= "[V4+ Styles]\n";
        $ass .= "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n";

        if ($subtitleType === 'anime' && empty($styles)) {
            $ass .= "Style: Default,GosmickSans,75,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2.5,2,2,15,15,55,1\n";
            $ass .= "Style: Atas,GosmickSans,75,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2.5,2,8,15,15,55,1\n";
            $ass .= "Style: Red PK,GosmickSans,75,&H000000DD,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2.5,2,8,15,15,55,1\n";
            $ass .= "Style: Signs,GosmickSans,75,&H00323232,&H000000FF,&H00EEEEEE,&H00000000,-1,0,0,0,100,100,0,0,1,2.5,2,5,10,10,55,1\n";
            $ass .= "Style: Outline,GosmickSans,75,&H00FFFFFF,&H000000FF,&H000000D7,&H00000000,-1,0,0,0,100,100,0,0,1,2.5,2,2,10,10,55,1\n";
        } elseif ($subtitleType === 'movie' && empty($styles)) {
            $ass .= "Style: Default,Panefresco 800wt,50,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,1.5,2,15,15,55,1\n";
        } elseif (!empty($styles)) {
            foreach ($styles as $style) {
                $ass .= $style . "\n";
            }
        }

        $ass .= "\n[Events]\n";
        $ass .= "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n";

        foreach ($subtitles as $sub) {
            $start = $this->convertTime($sub->start);
            $end = $this->convertTime($sub->end);
            $text = str_replace('<i>', '{\\i1}', $sub->text);
            $text = str_replace('</i>', '{\\i}', $text);
            $text = str_replace("\n", '\\N', $text);
            $text = str_replace("\r", '', $text);

            $ass .= "Dialogue: 0,$start,$end,{$sub->style},,0,0,0,,$text\n";
        }

        return $ass;
    }

    private function convertTime(string $time): string
    {
        if (str_contains($time, ',')) {
            $parts = explode(',', $time);
            $ms = (int)$parts[1];
            $cs = round($ms / 10);
            return $parts[0] . '.' . str_pad($cs, 2, '0', STR_PAD_LEFT);
        }
        return $time;
    }
}